"""add_onboarding_profile_fields

Revision ID: dbade63cc853
Revises: 70595713c688
Create Date: 2026-09-28 19:18:38.120112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbade63cc853'
down_revision: Union[str, None] = '70595713c688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('school', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('study_goal', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('weekly_hours', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('study_time', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('confidence_level', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'confidence_level')
    op.drop_column('users', 'study_time')
    op.drop_column('users', 'weekly_hours')
    op.drop_column('users', 'study_goal')
    op.drop_column('users', 'district')
    op.drop_column('users', 'school')
    op.drop_column('users', 'language')
    # ### end Alembic commands ###
